project:
  type: website

website:
  title: "Sergio Huertas Hernández"
  navbar:
    left:
      - href: index.qmd
        text: "🏠 Home"
      - href: cv.qmd
        text: "📄 CV"
      - href: publicaciones.qmd
        text: "📚 Publications"
      - href: teaching.qmd
        text: "👨‍🏫 Teaching"
      - href: contacto.qmd
        text: "📩 Contact"

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    include-after-body: footer.html
    icon: fontawesome

editor: visual